export const sources = [
  {
    title: "My story so far",
    author: "McIlroy, Richie",
    publisher: "richiemcilroy.com",
    date: "27 December 2025",
    url: "https://www.richiemcilroy.com/posts/my-story-so-far",
  },
  {
    title: "Richie McIlroy (@richiemcilroy)",
    author: "McIlroy, Richie",
    publisher: "GitHub",
    date: "Profile",
    url: "https://github.com/richiemcilroy",
  },
  {
    title: "Sold all of our founder plans, now at $413 MRR",
    author: "McIlroy, Richie",
    publisher: "Indie Hackers",
    date: "14 September 2021",
    url: "https://www.indiehackers.com/post/sold-all-of-our-founder-plans-now-at-413-mrr-90e7a8963c",
  },
  {
    title: "I built a tool that generates your Stripe account extra revenue",
    author: "McIlroy, Richie",
    publisher: "Indie Hackers",
    date: "7 November 2021",
    url: "https://www.indiehackers.com/post/i-built-a-tool-that-generates-your-stripe-account-extra-revenue-dd60b44b65",
  },
  {
    title: "How I sold my $0 revenue SaaS side project for $4.5K",
    author: "McIlroy, Richie",
    publisher: "Indie Hackers",
    date: "24 January 2022",
    url: "https://www.indiehackers.com/post/how-i-sold-my-0-revenue-saas-side-project-for-4-5k-290062e6ef",
  },
  {
    title: "Show HN: Cap – open-source alternative to Loom",
    author: "mcilroy et al.",
    publisher: "Hacker News",
    date: "28 November 2023",
    url: "https://news.ycombinator.com/item?id=38445731",
  },
  {
    title: "Cap Public Beta Release",
    author: "McIlroy, Richie",
    publisher: "Cap",
    date: "25 April 2024",
    url: "https://cap.so/blog/cap-public-beta-launch",
  },
  {
    title: "Cap v0.3.0 – A New Direction",
    author: "McIlroy, Richie",
    publisher: "Cap",
    date: "28 September 2024",
    url: "https://cap.so/blog/cap-v03-launch",
  },
  {
    title: "Handling a Stripe Payment Attack During Our Product Hunt Launch",
    author: "McIlroy, Richie",
    publisher: "Cap",
    date: "30 November 2024",
    url: "https://cap.so/blog/handling-a-stripe-payment-attack",
  },
  {
    title: "A deep dive into our September 23rd outage and what we changed",
    author: "McIlroy, Richie; Allan, Brendan",
    publisher: "Cap",
    date: "23 September 2025",
    url: "https://cap.so/blog/september-23-outage-deep-dive",
  },
  {
    title: "Cap v0.5 is here",
    author: "McIlroy, Richie",
    publisher: "Cap",
    date: "27 May 2026",
    url: "https://cap.so/blog/cap-v05",
  },
  {
    title: "Cap is SOC 2 Type II and ISO 27001 certified",
    author: "McIlroy, Richie",
    publisher: "Cap",
    date: "3 August 2026",
    url: "https://cap.so/blog/soc2-type-ii-iso-27001",
  },
  {
    title: "Cap is now HIPAA compliant",
    author: "McIlroy, Richie",
    publisher: "Cap",
    date: "20 August 2026",
    url: "https://cap.so/blog/cap-is-hipaa-compliant",
  },
  {
    title: "Cap fundraising: US$1.25 million raised as a solo founder",
    author: "McIlroy, Richie",
    publisher:
      "Direct confirmation for this biography (not a public announcement)",
    date: "7 September 2026",
    url: undefined,
  },
  {
    title: "Just Start Building",
    author: "McIlroy, Richie",
    publisher: "richiemcilroy.com",
    date: "27 February 2026",
    url: "https://www.richiemcilroy.com/posts/just-start-building",
  },
  {
    title: "Taste is a moat",
    author: "McIlroy, Richie",
    publisher: "richiemcilroy.com",
    date: "5 March 2026",
    url: "https://www.richiemcilroy.com/posts/taste-is-a-moat",
  },
  {
    title: "25 Indie Makers To Watch in 2022",
    author: "Craven, Jade",
    publisher: "Indie Hackers",
    date: "2021",
    url: "https://www.indiehackers.com/post/25-indie-makers-to-watch-in-2022-6110e2672b",
  },
  {
    title: "Generating a full blog post with AI",
    author: "McIlroy, Richie",
    publisher: "Indie Hackers",
    date: "10 September 2021",
    url: "https://www.indiehackers.com/post/generating-a-full-blog-post-with-ai-8ce869c7c0",
  },
  {
    title: "Launched the MVP for my latest product",
    author: "McIlroy, Richie",
    publisher: "Indie Hackers",
    date: "17 February 2022",
    url: "https://www.indiehackers.com/post/launched-the-mvp-for-my-latest-product-3dea46b572",
  },
  {
    title: "Why I'm making my latest product open-source",
    author: "McIlroy, Richie",
    publisher: "Indie Hackers",
    date: "25 June 2022",
    url: "https://www.indiehackers.com/post/why-im-making-my-latest-product-open-source-94ea5b0f65",
  },
  {
    title: "Affordable referral marketing software for indie hackers",
    author: "McIlroy, Richie",
    publisher: "Indie Hackers",
    date: "24 August 2022",
    url: "https://www.indiehackers.com/post/affordable-referral-marketing-software-for-indie-hackers-8e82cd704e",
  },
  {
    title: "Fireside chat with Richie Mcilroy, founder of Cap",
    author: "Startup Grind Liverpool",
    publisher: "Startup Grind",
    date: "12 December 2024",
    url: "https://www.startupgrind.com/events/details/startup-grind-liverpool-presents-fireside-chat-with-richie-mcilroy-founder-of-cap/",
  },
  {
    title: "Add support for playsinline (#19)",
    author: "McIlroy, Richie",
    publisher: "GitHub, merged pull request",
    date: "7 October 2021",
    url: "https://github.com/smrubin/react-lazy-media/pull/19",
  },
  {
    title: "Fix empty state text color in editor (#17521)",
    author: "McIlroy, Richie",
    publisher: "GitHub, merged pull request",
    date: "21 September 2023",
    url: "https://github.com/supabase/supabase/pull/17521",
  },
  {
    title: "[Bug fix] Org name not changing instantly (#737)",
    author: "McIlroy, Richie",
    publisher: "GitHub, merged pull request",
    date: "24 August 2024",
    url: "https://github.com/un/inbox/pull/737",
  },
  {
    title: "Accelerate Cargo development workflows (#1)",
    author: "McIlroy, Richie",
    publisher: "GitHub, merged pull request",
    date: "15 August 2026",
    url: "https://github.com/CapSoftware/cinder/pull/1",
  },
  {
    title: "Marriage to Olivia Mae Hanlon",
    author: "McIlroy, Richie",
    publisher: "Direct confirmation for this biography",
    date: "7 September 2026",
    url: undefined,
  },
  {
    title: "Olivia Hanlon",
    author: "Forbes editors",
    publisher: "Forbes",
    date: "9 April 2024",
    url: "https://www.forbes.com/profile/olivia-hanlon/",
  },
  {
    title: "Marketing Megastar: Meet BCU’s Alumna of the Year",
    author: "Birmingham City University",
    publisher: "BCU Alumni",
    date: "8 January 2026",
    url: "https://www.bcu.ac.uk/alumni/community/news-events/news/marketing-megastar-meet-bcus-alumna-of-the-year",
  },
  {
    title: "Open Source Hackathon Winners",
    author: "Wilson, Ant",
    publisher: "Supabase",
    date: "9 August 2021",
    url: "https://supabase.com/blog/hackathon-winners",
  },
  {
    title: "Cap has millions of downloads",
    author: "McIlroy, Richie",
    publisher: "Direct confirmation for this biography",
    date: "9 September 2026",
    url: undefined,
  },
] as const;

export const sections = [
  ["early-life", "Early life and education"],
  ["career", "Career"],
  ["early-career", "Web development", true],
  ["independent-products", "Independent products", true],
  ["cap", "Cap", true],
  ["funding", "Funding", true],
  ["open-source", "Open-source contributions"],
  ["writing", "Writing and public presence"],
  ["public-posts", "Selected public posts", true],
  ["personal-life", "Personal life"],
  ["references", "References"],
  ["external-links", "External links"],
] as const;
